/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.edtl.edtl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
} // Model
