/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.edtl.edtl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>w</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.edtl.edtl.w#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getw()
 * @model
 * @generated
 */
public interface w extends Model
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.edtl.edtl.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getw_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getElements();

} // w
