/*
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.edtl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEdtlScopeProvider extends DelegatingScopeProvider {
}
